name: Publish

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: npm build
        run: |
          cd ./web
          npm ci
          npm run build --if-present
        env:
          HISCORES_URL: "https://mickelsonosrs.azurewebsites.net/api/GetHiScores"
          REFETCH_INTERVAL: 300000
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          cd ./web
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>" -t true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
